---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana
  name: grafana-pvc
  namespace: benchmark
spec:
  storageClassName: cvs-premium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
      - name: grafana-vol
        persistentVolumeClaim:
          claimName: grafana-pvc
      initContainers:
      - name: take-ownership
        image: busybox
        command: ['sh', '-c', 'chown 472:472 "/var/lib/grafana"']
        volumeMounts:
        - mountPath: "/var/lib/grafana"
          name: grafana-vol
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/grafana"
          name: grafana-vol
      restartPolicy: Always
---
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  labels:
    app: grafana
  namespace: benchmark
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: grafana
